### ISSUE TITLE
Handle svg usage in styles (svg loader extract mode)

### ISSUE THREAD

**Issue by CPatchane** [webpack-contrib/mini-css-extract-plugin#103]
Hi here 👋 

I did use some SVG files directly in style codes (CSS or stylus) and for now, it was handled correctly by ETWP. When I use MCEP, it doesn't handle it and the SVG loader throws errors like:

```
ERROR in ./index.css
Module build failed: ModuleBuildError: Module build failed: ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin
    at Object.loader (test-webpack-4-svg/node_modules/svg-sprite-loader/lib/loader.js:54:13)
    at runLoaders (test-webpack-4-svg/node_modules/webpack/lib/NormalModule.js:236:20)
    at test-webpack-4-svg/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at test-webpack-4-svg/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (test-webpack-4-svg/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (test-webpack-4-svg/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (test-webpack-4-svg/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (test-webpack-4-svg/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (test-webpack-4-svg/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at test-webpack-4-svg/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ./index.js 1:0-21

ERROR in ./icon-cozy.svg
    Module build failed: ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin
        at Object.loader (test-webpack-4-svg/node_modules/svg-sprite-loader/lib/loader.js:54:13)
     @ ./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/lib??postcss!./index.css 7:100-126
```

I may miss something out but the `svg-sprite-loader`, in [extract mode](https://github.com/kisenka/svg-sprite-loader/blob/0f4d0413889fac6ddf82d2c5a2108b9760c6ccd0/examples/extract-mode/README.md), lets the extract-loader handling images by returning the URLs which are not correctly processed here. I don't have this issue using Webpack 3 and ETWP.

I created a repository to reproduce this issue: https://github.com/CPatchane/test-webpack4-svg

I hope this will help.

**Comment by evilebottnawi** [comment]
@CPatchane look on error, you don't add `SpriteLoaderPlugin` in plugin array

**Comment by evilebottnawi** [comment]
@CPatchane Yes, looks like bug in `svg-sprite-loader`. We use same logic for `ETWP`, but need depply investigate, feel free to debug and search problem, also you can create issue inside `svg-sprite-loader`

**Comment by evilebottnawi** [comment]
@CPatchane problem still exists?

**Comment by CPatchane** [comment]
I didn't had time to create a repo with this bug but I found this issue on `svg-sprite-loader` https://github.com/kisenka/svg-sprite-loader/issues/271. I think it could be related.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/kisenka/svg-sprite-loader/issues/271, feel free to feedback
