### ISSUE TITLE
mini-css-extract-plugin  and tailwind use error

### ISSUE THREAD

**Issue by ygs-code** [webpack-contrib/mini-css-extract-plugin#1109]
webpack and  mini-css-extract-plugin  and tailwind use error ，

error info：

ERROR in static/css/index~2dd625ae.5979476b.css
static/css/index~2dd625ae.5979476b.css from Css Minimizer plugin
Error: Unexpected '/'. Escaping special characters with \ may help.
    at E:\code\webpack-cli\static\css\index~2dd625ae.5979476b.css:1:1
    at Root._error (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:131:16)
    at Root.error (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\selectors\root.js:30:19)
    at Parser.error (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:598:21)
    at Parser.unexpected (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:612:17)
    at Parser.combinator (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:526:12)
    at Parser.parse (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:900:14)
    at Parser.loop (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:856:12)
    at new Parser (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\parser.js:124:10)
    at Processor._root (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\processor.js:40:18)
    at Processor._runSync (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\processor.js:78:21)
    at Processor.processSync (E:\code\webpack-cli\node_modules\postcss-selector-parser\dist\processor.js:164:23)
    at E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss-minify-selectors\src\index.js:250:45
    at E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\container.js:375:18
    at E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\container.js:303:18
    at Root.each (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\container.js:53:16)
    at Root.walk (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\container.js:300:17)
    at Root.walkRules (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\container.js:373:19)
    at OnceExit (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss-minify-selectors\src\index.js:232:11)
    at LazyResult.runAsync (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\lazy-result.js:298:21)
    at async cssnanoMinify (eval at transform (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\dist\minify.js:79:28), <anonymous>:95:18)
    at async minify (E:\code\webpack-cli\node_modules\css-minimizer-webpack-plugin\dist\minify.js:37:26)

**Comment by alexander-akait** [comment]
please open and issue in `postcss-selector-parser` and provide example if code which cause of it, we can't fix it here, thank you
