### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by miladkc** [webpack-contrib/mini-css-extract-plugin#198]
I have no idea about the things you asked me to provide, because I'm not using your module directly at all. I just have a routine angular application, and now I'm getting this error:

```
Cannot find module 'webpack'
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Taak\PixelearnWeb\school\node_modules\mini-css-extract-plugin\dist\index.js:15:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Taak\PixelearnWeb\school\node_modules\mini-css-extract-plugin\dist\cjs.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

**Comment by evilebottnawi** [comment]
@miladkc `rm -rf node_modules && npm i`

**Comment by tvthatsme** [comment]
We have same issue, ci only.
solution didn't work for us.
mini-css-extract-plugin is a dep of next.js in our case.
"version": "0.8.0"

**Comment by evilebottnawi** [comment]
Please open issue in `next.js`

**Comment by bingyang519** [comment]
Link globally installed package to your project
`npm link webpack`
