### ISSUE TITLE
`module._compile` has failed when executing code through less-loader

### ISSUE THREAD

**Issue by aleen42** [webpack-contrib/mini-css-extract-plugin#213]
### Version

plugin: 0.4.1
webpack: 4.4.1

### Configuration

```js
module.exports = {
    /** ... */
    module: {
        rules: [
            {
                test : /ui\.less$/,
                use  : [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    {
                        loader  : 'postcss-loader',
                        options : {
                            ident   : 'postcss',
                            plugins : [require('postcss-opacity')(), require('autoprefixer')({browsers : ['defaults', 'not ie < 8']})],
                        },
                    },
                    'less-loader',
                ],
            },
        ],
    },
};
```

### Stack Traces

```
ERROR in script/ui/ui.less
Module build failed: ReferenceError: self is not defined
at node_modules\css-loader\index.js!node_modules\less-loader\dist\cjs.js!web.modules\coremail.XT5\src\XT5\@project.revision@\script\ui\ui.less:62:35
at Object.<anonymous> (node_modules\css-loader\index.js!node_modules\less-loader\dist\cjs.js!web.modules\coremail.XT5\src\XT5\@project.revision@\script\ui\ui.less:69:10)
at Module._compile (module.js:571:32)
at exec (node_modules\mini-css-extract-plugin\dist\loader.js:55:10)
at childCompiler.runAsChild (node_modules\mini-css-extract-plugin\dist\loader.js:133:14)
at compile (node_modules\webpack\lib\Compiler.js:240:11)
at hooks.afterCompile.callAsync.err (node_modules\webpack\lib\Compiler.js:485:14)
at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules\tapable\lib\Hook.js:35:21)
    at compilation.seal.err (node_modules\webpack\lib\Compiler.js:482:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules\tapable\lib\Hook.js:35:21)
        at hooks.optimizeAssets.callAsync.err (node_modules\webpack\lib\Compilation.js:964:35)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
            at AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules\tapable\lib\Hook.js:35:21)
            at hooks.optimizeChunkAssets.callAsync.err (node_modules\webpack\lib\Compilation.js:955:32)
            @ script/app.js 6:0-23
            @ script/main.js
            @ ./build/XT5-webpack/entry-loader.js!script/main.js?chunk=XT5
```

And I found that the code parsed through `module._compile(code, filename);` has been formatted as "module.exports = xxx".

**Comment by evilebottnawi** [comment]
@aleen42 looks you have invalid configuration, please provide full reproducible test repo

**Comment by aleen42** [comment]
I have set up less-loader to compile Less to CSS, and I will check whether I have missed some configurations for less-loader later.

**Comment by aleen42** [comment]
This is the bug due to another local webpack plugin, I close it now, and thanks for answering.

**Comment by cobyrne09** [comment]
@aleen42 Do you recall what plugin? I am having a similar issue. Thanks!

**Comment by aleen42** [comment]
@cobyrne09 I don't really remember the case, and you can debug it by checking the input of `less-loader`.
