### ISSUE TITLE
Second build on watch error

### ISSUE THREAD

**Issue by ydegtyar** [webpack-contrib/mini-css-extract-plugin#243]
```
"webpack": "^4.16.4",
"mini-css-extract-plugin": "^0.4.1",
```
config
```
plugins: [
    new PhpManifestPlugin({
      output: manifestFileName,
      path: '/dist'
    }),
    new webpack.AutomaticPrefetchPlugin(),

    new webpack.HashedModuleIdsPlugin(),
    new MiniCssExtractPlugin({
      filename: inProduction ? "css/[name].[contenthash].css" : "css/[name].css",
      chunkFilename: inProduction ? "css/[id].[contenthash].css" : "css/[id].css"
    })
  ],
  optimization: {
    minimizer: [],
    splitChunks: {
      chunks: 'all',
    }
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              publicPath: '/public/dist/css'
            }
          },
          "css-loader"
        ]
      }
    ]
  }
```

Build work pretty well. But when I run it in watch mode after first changes module throw exceptions.

```ERROR in ./node_modules/flatpickr/dist/flatpickr.min.css (./node_modules/mini-css-extract-plugin/dist/loader.js??ref--4-0!./node_modules/css-loader!./node_modules/flatpickr/dist/flatpickr.min.css)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at childCompiler.runAsChild (/vagrant/application/node_modules/mini-css-extract-plugin/dist/loader.js:128:23)
    at compile (/vagrant/application/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1284:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1275:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1270:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1266:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/vagrant/application/node_modules/webpack/lib/Compilation.js:1203:27)
    at hooks.make.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:547:17)
    at _err0 (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/vagrant/application/node_modules/webpack/lib/Compilation.js:1054:12)
    at processModuleDependencies.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:980:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at runLoaders (/vagrant/application/node_modules/webpack/lib/NormalModule.js:286:20)
    at /vagrant/application/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /vagrant/application/node_modules/loader-runner/lib/LoaderRunner.js:179:20
    at context.callback (/vagrant/application/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at childCompiler.runAsChild (/vagrant/application/node_modules/mini-css-extract-plugin/dist/loader.js:128:14)
    at compile (/vagrant/application/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1284:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1275:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1270:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1266:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/vagrant/application/node_modules/webpack/lib/Compilation.js:1203:27)
    at hooks.make.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:547:17)
    at _err0 (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/vagrant/application/node_modules/webpack/lib/Compilation.js:1054:12)
    at processModuleDependencies.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:980:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/flatpickr/dist/flatpickr.min.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/mini-css-extract-plugin/dist/loader.js??ref--4-0!node_modules/css-loader/index.js!node_modules/flatpickr/dist/flatpickr.min.css:
    Entrypoint mini-css-extract-plugin = *
       1 module
    
    ERROR in ./node_modules/flatpickr/dist/flatpickr.min.css (./node_modules/css-loader!./node_modules/mini-css-extract-plugin/dist/loader.js??ref--4-0!./node_modules/css-loader!./node_modules/flatpickr/dist/flatpickr.min.css)
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    Error: Didn't get a result from child compiler
        at childCompiler.runAsChild (/vagrant/application/node_modules/mini-css-extract-plugin/dist/loader.js:128:23)
        at compile (/vagrant/application/node_modules/webpack/lib/Compiler.js:296:11)
        at hooks.afterCompile.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:553:14)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:33:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
        at compilation.seal.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:550:30)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
        at hooks.optimizeAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1284:35)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
        at hooks.optimizeChunkAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1275:32)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
        at hooks.additionalAssets.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1270:36)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
        at hooks.optimizeTree.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:1266:32)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/vagrant/application/node_modules/tapable/lib/Hook.js:35:21)
        at Compilation.seal (/vagrant/application/node_modules/webpack/lib/Compilation.js:1203:27)
        at hooks.make.callAsync.err (/vagrant/application/node_modules/webpack/lib/Compiler.js:547:17)
        at _err0 (eval at create (/vagrant/application/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
        at _addModuleChain (/vagrant/application/node_modules/webpack/lib/Compilation.js:1054:12)
        at processModuleDependencies.err (/vagrant/application/node_modules/webpack/lib/Compilation.js:980:9)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/flatpickr/dist/flatpickr.min.css:
        Entrypoint mini-css-extract-plugin = *
           2 modules
```

**Comment by ydegtyar** [comment]
The problem was in AutomaticPrefetchPlugin. After few tests, I just deleted it  and all works fine thanks. And for `mini-css-extract-plugin` in development what I have to use instead?

**Comment by evilebottnawi** [comment]
@ydegtyar `style-loader`
