### ISSUE TITLE
ChunkRenderError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by johnnyZTY** [webpack-contrib/mini-css-extract-plugin#304]
ERROR in ../node_modules/video.js/dist/video-js.css
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ChunkRenderError: Cannot read property 'map' of undefined
    at Compilation.createHash (D:\W\frontend\node_modules\webpack\lib\Compilation.js:2335:22)
    at hooks.optimizeTree.callAsync.err (D:\W\frontend\node_modules\webpack\lib\Compilation.js:1286:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\W\frontend\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\W\frontend\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (D:\W\frontend\node_modules\webpack\lib\Compilation.js:1242:27)
    at hooks.make.callAsync.err (D:\W\frontend\node_modules\webpack\lib\Compiler.js:546:17)
    at _err0 (eval at create (D:\W\frontend\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (D:\W\frontend\node_modules\webpack\lib\Compilation.js:1093:12)
    at processModuleDependencies.err (D:\W\frontend\node_modules\webpack\lib\Compilation.js:1005:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./js/component/video.jsx 8:0-36
 @ ./js/layout.jsx
 @ ./js/app.jsx

----------------------------------------------------------
I got many err like above. 
How does this happen ?

**Comment by evilebottnawi** [comment]
@johnnyZTY without reproducible test repo i can't help

**Comment by johnnyZTY** [comment]
> @johnnyZTY without reproducible test repo i can't help

Sorry , i am new coder and just use github not long.

Below is the code snippets and my webpack.config.js. And i use React in this project.

    optimization: {
        minimizer: [uglify],
        // runtimeChunk: 'single',
        splitChunks: {
            chunks: 'all',
            minSize: 30000,
            minChunks: 1,
            maxAsyncRequests: 5,
            maxInitialRequests: 3,
            automaticNameDelimiter: '~',
            name: 'commons',
            cacheGroups: {
                vendors: {
                    name: 'vendors',
                    test: /[\\/]node_modules[\\/]/,
                    priority: -10,
                },
                default: {
                    minChunks: 2,
                    priority: -20,
                    reuseExistingChunk: true,
                },
            },
        },
    },

https://github.com/johnnyZTY/debugRepo/blob/master/webpack.config.js

**Comment by evilebottnawi** [comment]
@johnnyZTY please create **minimum** reproducible test repo (we don't have enough time to debug bug projects) on errors, sorry

**Comment by gabn88** [comment]
Did you find a solution @johnnyZTY ?
