### ISSUE TITLE
mini-css-extract-plugin  large index.css error

### ISSUE THREAD

**Issue by cleverboy32** [webpack-contrib/mini-css-extract-plugin#354]
my index.css is complied from postcs. it contains my components style. so it large .
and if i delete it to be less, it can work.  The css config, i use `vue-cli3.0` default config.

`the index.css it look like this` 
```
.som-button,.som-button.som-button--error::after,.som-button.som-button--info::after,.som-button.som-button--plain--default::after,.som-button.som-button--plain--error::after,.som-button.som-button--plain--info::after,.som-button.som-button--plain--primary::after,.som-button.som-button--plain--success::after,.som-button.som-button--plain--warn::after,.som-button.som-button--primary::after,.som-button.som-button--success::after,.som-button.som-button--warn::after{border-width:0}.som-button,.som-modal .som-prompt-msgbox,.som-radio .som-radio-input,.som-tabs button{outline:0;-webkit-appearance:none}.som-accordion .som-list-item,.som-button,.som-list-item,.som-list-item.som-list-item-access,.som-modal__btn,.som-radio--button.som-radio__label,.som-radio__label,.som-tab-item{-webkit-tap-highlight-color:transparent}.som-input__elm,.som-nav-bar__title{text-overflow:ellipsis;white-space:nowrap}:root{--primary:#ff571a;--primary-text:var(--primary);--primary-press:#e54e17;--primary-disable:#ff9a76;--primary-selected:#ffeee8;--background-notice:#fff2bd;--background-warning:#fff1f0;--text-title:#1b1c33;--text-body:#5e5e66;--text-caption:#8d8e99;--text-hint:#b0b1b8;--line-b:#d7d7db;--line-c:#ededf0;--press:#e3e3e6;--background-page:#f2f3f5;--background-block:#f7f8fa;--text-white:#fff;--mask:#000;--primary-highlight:var(--primary);--primary-disable-select-color:#ffd2c2;--fs12:12px;--fs14:14px;--fs15:15px;--fs16:16px;--fs18:18px;--fs20:20px;--fs22:22px;--fs24:24px;--border-radius-base:4px;--border-radius-large:6px;--border-radius-small:3px;--font-family:PingFangSC-Regular,Helvetica,"Droid Sans",Arial,sans-serif;--all-transition:all .3s cubic-bezier(.645,.045,.355,1);--fade-linear-transition:opacity 200ms linear;--md-fade-transition:transform 300ms cubic-bezier(.23, 1, .32, 1) 100ms,opacity 300ms cubic-bezier(.23, 1, .32, 1) 100ms;--border-transition-base:border-color .2s cubic-bezier(.645,.045,.355,1);--color-transition-base:color .2s cubic-bezier(.645,.045,.355,1);
.....
```

`the error`
```
Module build failed (from ./node_modules/@vue/cli-service/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 19
    at /Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/@souche-ui/som-ui/lib/styles/index.css:1:92001
    at Parser.error (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-values-parser/lib/parser.js:
127:11)
    at Parser.operator (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-values-parser/lib/parser.
js:183:18)
    at Parser.parseTokens (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-values-parser/lib/pars
er.js:245:14)
    at Parser.loop (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-values-parser/lib/parser.js:1
32:12)
    at Parser.parse (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-values-parser/lib/parser.js:
51:17)
    at getReplacedValue (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-env-function/index.cjs.j
s:109:37)
    at root.walk.node (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-env-function/index.cjs.js:271:35)
    at /Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss/lib/container.js:131:17)
    at /Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss/lib/container.js:131:17)
    at Object.<anonymous> (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-env-function/index.cjs.js:267:14)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/postcss-env-function/index.cjs.js:12:24)
    at runLoaders (/Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/webpack/lib/NormalModule.js:286:20)
    at /Users/cleverboy32/Documents/work/channel-cube-map-mobile/node_modules/loader-runner/lib/LoaderRunner.js:364:11
```

**Comment by evilebottnawi** [comment]
@cleverboy32 you have invald css what can be parsed by `postcss-values-parser`, problem in `postcss-env-function`, please post issue in their repo with reproducible test repo, thanks!
