### ISSUE TITLE
[HMR issue] Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by morgs32** [webpack-contrib/mini-css-extract-plugin#420]
* Operating System: macOS
* Node Version: v9.11.2
* NPM Version: 6.4.1
* webpack Version: webpack@^4.6.0
* mini-css-extract-plugin Version: 0.7.0

### Expected Behavior
Expecting HMR to work when I change any style in `client.scss`

### Actual Behavior
```
ERROR in ./src/client.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at childCompiler.runAsChild (/Users/morganintrator/GitHub/basic/node_modules/mini-css-extract-plugin/dist/loader.js:144:23)
    at compile (/Users/morganintrator/GitHub/basic/node_modules/webpack/lib/Compiler.js:306:11)
    at hooks.afterCompile.callAsync.err (/Users/morganintrator/GitHub/basic/node_modules/webpack/lib/Compiler.js:631:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/morganintrator/GitHub/basic/node_modules/webpack/lib/Compiler.js:628:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/morganintrator/GitHub/basic/node_modules/webpack/lib/Compilation.js:1325:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/morganintrator/GitHub/basic/node_modules/webpack/lib/Compilation.js:1316:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/morganintrator/GitHub/basic/node_modules/webpack/lib/Compilation.js:1311:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/morganintrator/GitHub/basic/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
 @ ./src/client.js 6:0-23
 @ multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client
```

### How Do We Reproduce?
Here's a basic repro: https://github.com/morgs32/afterjs-mini-css-extract-plugin

**Comment by morgs32** [comment]
@ScriptedAlchemy Do you have a good working example of HMR that I can study? Since you did the work on it?

**Comment by morgs32** [comment]
![image](https://user-images.githubusercontent.com/1364795/60922346-56927400-a251-11e9-84a8-194dd1726c1e.png)

**Comment by evilebottnawi** [comment]
Please provide **minimum** reproducible test repo, you try all commands in you repo and all works fine, i think better create issue in `razzle` repo

**Comment by dtothefp** [comment]
If HotModuleReplacementPlugin as option `multiStep: true` this happens. Razzle has this internally for client build
