### ISSUE TITLE
Lots of deprecation warnings in webpack-5-beta-16

### ISSUE THREAD

**Issue by saravanan10393** [webpack-contrib/mini-css-extract-plugin#544]
- Operating System: MacOs
- Node Version: 12
- NPM Version: 6
- webpack Version: 5.0-beta-16
- mini-css-extract-plugin Version: ^0.9

### Expected Behavior
Support for webpack-5 without any warnings

### Actual Behavior
There are lots of deprecation warnings bloating up my terminal

### Code

```js
[DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
    at /Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/mini-css-extract-plugin/dist/index.js:137:53
    at Hook.eval [as call] (eval at create (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10)
```

```js
[DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
    at getNormalModuleLoader (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/lib/Compilation.js:270:39)
    at Object.get normalModuleLoader [as normalModuleLoader] (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/lib/Compilation.js:495:12)
    at /Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/mini-css-extract-plugin/dist/loader.js:99:23

```

```js
[DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
    at Function.getChunkGraphForModule (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/lib/ChunkGraph.js:1277:10)
    at NormalModule.get id [as id] (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/lib/Module.js:130:21)
    at findModuleById (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/mini-css-extract-plugin/dist/loader.js:69:16)
    at /Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/mini-css-extract-plugin/dist/loader.js:175:26

```

```js
 [DEP_WEBPACK_MAIN_TEMPLATE_OUTPUT_OPTIONS] DeprecationWarning: MainTemplate.outputOptions is deprecated (use Compilation.outputOptions instead)
    at /Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/mini-css-extract-plugin/dist/index.js:233:28
```

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/330
