### ISSUE TITLE
Issue with css-loader 4.1.1

### ISSUE THREAD

**Issue by nstuyvesant** [webpack-contrib/mini-css-extract-plugin#558]
- Operating System: macOS
- Node Version: 14.7.0
- NPM Version: 6.14.7
- webpack Version: 4.44.1
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

This will work:
```
        {
          test: /\.(sa|sc|c)ss$/,
          include: [
            path.resolve(__dirname, 'client/app/app.scss')
          ],
          use: [
            // In development, CSS is in app.bundle.js. In production, CSS is in app.[hash].css.
            MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader', // https://github.com/webpack-contrib/css-loader
              options: {
                modules: {
                  type: 'icss',
                  exportOnlyLocals: true
                }
              }
            },
            { // Shrinks CSS file by 12K
              loader: 'postcss-loader', // https://github.com/postcss/postcss-loader
              options: {
                plugins: () => [autoprefixer()]
              }
            },
            {
              loader: 'sass-loader', // https://github.com/webpack-contrib/sass-loader
            }
          ]
        }
```

### Actual Behavior

```
ERROR in ./client/app/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules has an unknown property 'type'. These properties are valid:
   object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashPrefix?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
    at validate (/Users/nates/dev/shy/node_modules/schema-utils/dist/validate.js:96:11)
    at Object.loader (/Users/nates/dev/shy/node_modules/css-loader/dist/index.js:36:28)
    at /Users/nates/dev/shy/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/nates/dev/shy/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/nates/dev/shy/node_modules/loader-runner/lib/LoaderRunner.js:233:18
 @ ./client/app/app.module.js 70:0-20
```

### Code

See above

### How Do We Reproduce?

Install css-loader@4.1.1 and use Webpack configuration provided above.

**Comment by evilebottnawi** [comment]
`type: 'icss',` is not implemented and it should be on `css-loader`, you can find an issue in `css-loader` repo

**Comment by evilebottnawi** [comment]
Ref: https://github.com/webpack-contrib/css-loader/issues/1134

**Comment by nstuyvesant** [comment]
It also errors if I comment out that particular item.

**Comment by evilebottnawi** [comment]
Because it is not implemented yet
