### ISSUE TITLE
Didn't get a result from child compiler

### ISSUE THREAD

**Issue by mjmnagy** [webpack-contrib/mini-css-extract-plugin#568]
I am trying to write a `vue` component library that will work in `nuxt` and `vue`.

The issue i was originally having was `document is not defined` when using `Extract CSS`. from reading, i understand the `css-loader` webpack settings need to be adjusted to use a different module (one that isnt using `document`). 

I have downloaded(npm) the new webpack module(https://webpack.js.org/plugins/mini-css-extract-plugin/) and copied in the example code without any luck. 

The below is an example of the error i get for every component

          error  in ./components/inputs/shared/desc.vue?vue&type=style&index=0&id=08898866&scoped=true&lang=css&
          Module build failed (from ./node_modules/@vue/cli-service/node_modules/mini-css-extract-plugin/dist/loader.js):
          ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
          Error: Didn't get a result from child compiler
          at childCompiler.runAsChild (B:\lib\node_modules\mini-css-extract-plugin\dist\loader.js:159:23)
          at compile (B:\lib\node_modules\webpack\lib\Compiler.js:343:11)
          at hooks.afterCompile.callAsync.err (B:\lib\node_modules\webpack\lib\Compiler.js:681:15)
          at AsyncSeriesHook.eval [as callAsync] (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
          at AsyncSeriesHook.lazyCompileHook (B:\lib\node_modules\tapable\lib\Hook.js:154:20)
          at compilation.seal.err (B:\lib\node_modules\webpack\lib\Compiler.js:678:31)
          at AsyncSeriesHook.eval [as callAsync] (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
          at AsyncSeriesHook.lazyCompileHook (B:\lib\node_modules\tapable\lib\Hook.js:154:20)
          at hooks.optimizeAssets.callAsync.err (B:\lib\node_modules\webpack\lib\Compilation.js:1423:35)
          at AsyncSeriesHook.eval [as callAsync] (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
          at AsyncSeriesHook.lazyCompileHook (B:\lib\node_modules\tapable\lib\Hook.js:154:20)
          at hooks.optimizeChunkAssets.callAsync.err (B:\lib\node_modules\webpack\lib\Compilation.js:1414:32)
          at _promise0.then._result0 (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
          at process._tickCallback (internal/process/next_tick.js:68:7)
          at runLoaders (B:\lib\node_modules\webpack\lib\NormalModule.js:316:20)
          at B:\lib\node_modules\loader-runner\lib\LoaderRunner.js:367:11
          at B:\lib\node_modules\loader-runner\lib\LoaderRunner.js:182:20
          at context.callback (B:\lib\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
          at childCompiler.runAsChild (B:\lib\node_modules\mini-css-extract-plugin\dist\loader.js:159:14)
          at compile (B:\lib\node_modules\webpack\lib\Compiler.js:343:11)
          at hooks.afterCompile.callAsync.err (B:\lib\node_modules\webpack\lib\Compiler.js:681:15)
          at AsyncSeriesHook.eval [as callAsync] (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
          at AsyncSeriesHook.lazyCompileHook (B:\lib\node_modules\tapable\lib\Hook.js:154:20)
          at compilation.seal.err (B:\lib\node_modules\webpack\lib\Compiler.js:678:31)
          at AsyncSeriesHook.eval [as callAsync] (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
          at AsyncSeriesHook.lazyCompileHook (B:\lib\node_modules\tapable\lib\Hook.js:154:20)
          at hooks.optimizeAssets.callAsync.err (B:\lib\node_modules\webpack\lib\Compilation.js:1423:35)
          at AsyncSeriesHook.eval [as callAsync] (eval at create (B:\lib\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
          at AsyncSeriesHook.lazyCompileHook (B:\lib\node_modules\tapable\lib\Hook.js:154:20)
          at hooks.optimizeChunkAssets.callAsync.err (B:\lib\node_modules\webpack\lib\Compilation.js:1414:32)

I have been looking on the interweb for hours now and cannot seem to find a solution.

I have been looking at the `API Docs` https://ssr.vuejs.org/guide/build-config.html#server-config and cannot seem to find something that works. Additionally i tied deleting `node_modules` 

      //vue.config.js
    const path = require('path')
    const MiniCssExtractPlugin = require('mini-css-extract-plugin')

    module.exports = {
      outputDir: 'dist',
      lintOnSave: false,
      css: {
        extract: true //false
      },
      configureWebpack: {
        devtool: 'source-map',
        plugins: [
          new MiniCssExtractPlugin({
            filename: '[name].css',
            chunkFilename: '[id].css',
            ignoreOrder: false
          })
        ],
        module: {
          rules: [
            {
              test: /\.css$/i,
              use: [MiniCssExtractPlugin.loader, 'css-loader']
            }
          ]
        },
        resolve: {
          alias: {
            '@': path.resolve(__dirname)
          }
        }
      }
    }

Thanks

**Comment by evilebottnawi** [comment]
Please open an issue in `vue` repo and do not ignore the issue template, without this information I can help, you need help, please fill out the issue template and I will reopen

**Comment by mjmnagy** [comment]
> Please open an issue in `vue` repo and do not ignore the issue template, without this information I can help, you need help, please fill out the issue template and I will reopen

https://github.com/mjmnagy/vue-error-2020-08-26

**Comment by evilebottnawi** [comment]
@mjmnagy vue-cli support css out of box, you don't need this, now you have twice added loader and plugin

**Comment by mjmnagy** [comment]
> 
> 
> @mjmnagy vue-cli support css out of box, you don't need this, now you have twice added loader and plugin

Are you saying this error is due to me "twice added loader and plugin"

**Comment by evilebottnawi** [comment]
yes

**Comment by mjmnagy** [comment]
I see it actually in the `vue-cli` documents now(so i must be doing circles).

![image](https://user-images.githubusercontent.com/13066887/91484218-24354300-e866-11ea-809a-c5a62b0e82d5.png)

How can i tell the plugin to make it SSR ready? It is checking the `<link>` tags on the server side and fails?

**Comment by evilebottnawi** [comment]
@mjmnagy Please use stackoverflow or gitter for question, maybe better ask this in `vue-cli` repo
