### ISSUE TITLE
mini-css-extract-plugin Callback was already called.

### ISSUE THREAD

**Issue by LeachZhou** [webpack-contrib/mini-css-extract-plugin#574]
I used mini-css-extract-plugin and configured this , but it has this problem, what should I do?

```js
{
    test: /\.css$/i,
    exclude: /node_modules/,
    use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
    ]
},
{
    test: /\.(htm|html)$/i,
    exclude: /node_modules/,
    use: [
        {
            loader: 'html-loader',
            options: {
                attrs: ['img:src', 'link:href']
            }
        },
    ]
},
```

```js
/Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:16:11)
    at /Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:2818:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You forget to add the plugin
