### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Ralvke** [webpack-contrib/mini-css-extract-plugin#6]
Plugin supports modules/postcss?

### Stack trace
```
 ~/D/P/M/frontend » yarn build:prod
yarn run v1.3.2
$ NODE_ENV=production webpack
(node:3898) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:3898) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at OriginalSource.size (/home/ralvke/.../frontend/node_modules/webpack-sources/lib/Source.js:17:23)
    at ConcatSource.size (/home/ralvke/.../frontend/node_modules/webpack-sources/lib/ConcatSource.js:52:61)
    at CachedSource.size (/home/ralvke/.../frontend/node_modules/webpack-sources/lib/CachedSource.js:35:42)
    at obj.assets.compilationAssets.map.asset (/home/ralvke/.../frontend/node_modules/webpack/lib/Stats.js:347:39)
    at Array.map (<anonymous>)
    at Stats.toJson (/home/ralvke/.../frontend/node_modules/webpack/lib/Stats.js:344:6)
    at Stats.toString (/home/ralvke/.../frontend/node_modules/webpack/lib/Stats.js:621:20)
    at compilerCallback (/home/ralvke/.../frontend/node_modules/webpack-cli/bin/webpack.js:477:32)
    at hooks.done.callAsync.err (/home/ralvke/.../frontend/node_modules/webpack/lib/Compiler.js:152:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ralvke/.../frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ralvke/.../frontend/node_modules/tapable/lib/Hook.js:35:21)
    at onCompiled (/home/ralvke/.../frontend/node_modules/webpack/lib/Compiler.js:150:21)
    at hooks.afterCompile.callAsync.err (/home/ralvke/.../frontend/node_modules/webpack/lib/Compiler.js:470:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ralvke/.../frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ralvke/.../frontend/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/home/ralvke/.../frontend/node_modules/webpack/lib/Compiler.js:467:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ralvke/.../frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ralvke/.../frontend/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/home/ralvke/.../frontend/node_modules/webpack/lib/Compilation.js:957:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ralvke/.../frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ralvke/.../frontend/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/home/ralvke/.../frontend/node_modules/webpack/lib/Compilation.js:948:32)
    at _err1 (eval at create (/home/ralvke/.../frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
    at /home/ralvke/.../frontend/node_modules/uglifyjs-webpack-plugin/dist/index.js:262:11
    at step (/home/ralvke/.../frontend/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/home/ralvke/.../frontend/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at tryCatcher (/home/ralvke/.../frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ralvke/.../frontend/node_modules/bluebird/js/release/promise.js:614:10)

Done in 83.93s.
```

### Config
```js
plugins: [new MiniCssExtractPlugin()],
rules: [
  {
    test: /\.sss$/,
    use: [
      MiniCssExtractPlugin.loader,
      {
        loader: "css-loader",
        options: {
          importLoaders: 1,
          modules: true,
          localIdentName: "[hash:base64:8]"
        }
      },
      {loader: "postcss-loader"}
    ]
  },
]
```

### Environment
Node: `9.6.1`
Yarn: `1.3.2`
Webpack: `4.1.0`
mini-css-extract-plugin: `0.1.0`

**Comment by developer-lindner** [comment]
Example:

```
{
    test: /\.(scss|css)$/,
    use: [
        MiniCssExtractPlugin.loader,
        {
            loader: "css-loader",
            options: {
                minimize: {
                    safe: true
                }
            }
        },
        {
            loader: "postcss-loader",
            options: {
                autoprefixer: {
                    browsers: ["last 2 versions"]
                },
                plugins: () => [
                    autoprefixer
                ]
            },
        },
        {
            loader: "sass-loader"
        }
    ]
},
```
Maybe helps you out...

**Comment by Ralvke** [comment]
@developer-lindner it's disables css modules

BTW, the whole problem was in webpack-merge, which injects `style-loader` into production build (facepalm). Closing
