### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Hyperblaster** [webpack-contrib/mini-css-extract-plugin#642]
- MacOS Catalina 10.15.6
- Node v12.18.0
- NPM 6.14.8
- webpack Version: 4.44.2
   webpack-cli: 3.3.12
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

Using Webpack to publish a Vue Component Library, and needing to extract a single CSS file with all the css from the components. But it fails when using the mini-css-extract-plugin

### Actual Behavior

Failing on build with this error/stacktrace
```
/node_modules/mini-css-extract-plugin/dist/index.js:66
    const resource = this._identifier.split('!').pop();
                                      ^
TypeError: Cannot read property 'split' of undefined
    at CssModule.nameForCondition (/node_modules/mini-css-extract-plugin/dist/index.js:66:39)
    at Function.checkTest (/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:335:52)
    at Object.fn [as getCacheGroups] (/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:272:35)
```

### Code

webpack.config.js looks like this
```js
{
module: {
    rules: [{
            test: /\.(s*)css$/,
            use: [
                MiniCssExtractPlugin.loader, //If i remove this everything works fine
                'vue-style-loader',
                'css-loader',
                'sass-loader',
                {
                    loader: 'sass-resources-loader',
                    options: {
                        resources: [
                            './src/variables.scss',
                        ]
                    },
                },
            ]
        },
    },
    plugins: [
        new VueLoaderPlugin(),
        new MiniCssExtractPlugin({
            filename: 'EXTRACTED.css',
            chunkFilename: "[name].css"
        })
    ],
    optimization: {
        splitChunks: {
            cacheGroups: {
                styles: {
                    name: 'styles',
                    test: /\.(s*)css$/,
                    chunks: 'all',
                    enforce: true,
                },
            },
        },
    },
}
```

Any idea with what i'm doing wrong?

**Comment by evilebottnawi** [comment]
Please open an issue in `vue-style-loader`, can't reproduce

**Comment by evilebottnawi** [comment]
Also

> However, since this is included as a dependency and used by default in vue-loader, in most cases you don't need to configure this loader yourself.
