### ISSUE TITLE
TypeError: Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by interposition** [webpack-contrib/mini-css-extract-plugin#645]
- Operating System: win 10 x64
- Node Version: v10.16.0
- NPM Version: 6.9.0
- webpack Version: 5.3.2
- mini-css-extract-plugin Version: 1.2.0

### Actual Behavior

`ERROR in ./src/scss/main.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    TypeError: Cannot read property 'tapAsync' of undefined
        at ExternalModuleFactoryPlugin.apply (C:\proj\assets\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:42:39)
        at compiler.hooks.compile.tap (C:\proj\assets\node_modules\webpack\lib\ExternalsPlugin.js:30:63)
        at SyncHook.eval [as call] (eval at create (C:\proj\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
        at SyncHook.lazyCompileHook (C:\proj\node_modules\tapable\lib\Hook.js:154:20)
        at hooks.beforeCompile.callAsync.err (C:\proj\node_modules\webpack\lib\Compiler.js:615:23)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\proj\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook (C:\proj\node_modules\tapable\lib\Hook.js:154:20)
        at Compiler.compile (C:\proj\node_modules\webpack\lib\Compiler.js:612:28)
        at Compiler.runAsChild (C:\proj\node_modules\webpack\lib\Compiler.js:291:8)
        at Object.pitch (C:\proj\assets\node_modules\mini-css-extract-plugin\dist\loader.js:121:17)
     @ ./src/js/main.js 9:0-29
`
### Code

```const path = require('path');
const BUILD_PATH = path.resolve(__dirname, "../public/assets/js");
// styles
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const autoprefixer = require('autoprefixer');


const FRONT = {
    optimization: {
        splitChunks: {
            chunks:  'async',
        },
    },
    entry: {
        'scripts': './src/js/main.js',
    },
    output: {
        path:  BUILD_PATH,
        filename: "[name].js",
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: './../css/style.css',
            ignoreOrder: true,
        }),
    ],
    module: {
        rules: [
            {
                test: /\.(scss|sass|css)$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: 'css-loader',
                    }, {
                        loader: 'resolve-url-loader',
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            plugins: [
                                autoprefixer({
                                    overrideBrowserslist:['ie >= 11', 'last 4 version']
                                })
                            ],
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                        }
                    }
                ]
            }
        ],
    },
};

module.exports = [
    FRONT,
];
```

### How Do We Reproduce?
Run build

**Comment by evilebottnawi** [comment]
Please fix the issue template and I will reopen 

> How Do We Reproduce?
> Run build

Not help, because I can't reproduce,

**Comment by jblondeau2** [comment]
What a shitty plugin! I have the exact same problem using webpack 5.11.1, and and still no solution for now...

**Comment by crazyair** [comment]
+1

**Comment by mariowix** [comment]
I read that plugins need to update to support new versions of webpack. Maybe something like that is happening with this plugin.

[Here is the source](https://github.com/jantimon/html-webpack-plugin/issues/1049#issuecomment-423142837)

I had the same problem, and downgrading the **webpack** version to **4.45.0** works for me.
