### ISSUE TITLE
Bug with Webpack 5 + Terser 

### ISSUE THREAD

**Issue by CYB3RL1F3** [webpack-contrib/mini-css-extract-plugin#674]
Hello,
I meet a problem while trying to use mini css extract plugin with Webpack 5 and Terser. It simply doesn't work and I don't have any clue what to do... :/

Errorr: 

```
ERROR in ./assets/main.css
Module build failed (from ../node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at serialize (/Server/cyberlife/node_modules/serialize-javascript/index.js:192:20)
    at compiler.hooks.compilation.tap.compilation (/Server/cyberlife/node_modules/terser-webpack-plugin/dist/index.js:567:53)
    at Hook.eval [as call] (eval at create (/Server/cyberlife/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:112:1)
    at Hook.CALL_DELEGATE [as _call] (/Server/cyberlife/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Server/cyberlife/node_modules/webpack/lib/Compiler.js:988:26)
    at hooks.beforeCompile.callAsync.err (/Server/cyberlife/node_modules/webpack/lib/Compiler.js:1029:29)
    at Hook.eval [as callAsync] (eval at create (/Server/cyberlife/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Server/cyberlife/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Server/cyberlife/node_modules/webpack/lib/Compiler.js:1024:28)
```

Configuration : 

In module.rules : 
```
{
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader
          },
          {
            loader: 'css-loader',
            options: {
              fallback: 'style-loader',
              esModule: false,
              modules: {
                localIdentName: '[local]__[fullhash:base64:5]'
              },
              sourceMap: !isProduction,
              importLoaders: 1
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                ident: 'postcss',
                plugins: [
                  require('postcss-import')({ addDependencyTo: webpack }),
                  require('postcss-url')(),
                  require('postcss-cssnext')(),
                  require('postcss-reporter')(),
                  require('postcss-browser-reporter')({
                    disabled: isProduction
                  })
                ]
              }
            }
          }
        ],
        sideEffects: true,
      },

```

In plugins: 
```
new MiniCssExtractPlugin({
      filename: '[name].[fullhash].css',
      chunkFilename: '[name].[fullhash].css'
    }),
    new TerserPlugin({
  parallel: false,
  extractComments: "all",
  terserOptions: {
    toplevel: true,
    keep_classnames: false,
    keep_fnames: false,
    parse: {},
    compress: {
      dead_code: true,
      directives: true,
      drop_console: true,
      inline: true,
      ecma: 5,
      if_return: true,
      join_vars: true,
      reduce_vars: true,
      evaluate: true
    },
    mangle: {
      toplevel: true,
      module: true
    },
    output: {
      beautify: false,
      // code: false,
      ast: true,
    },
    nameCache: null,
    ie8: false
  },
}),
new CompressionPlugin({
      filename: '[name].[fullhash].gz[query]',
      algorithm: 'gzip',
      test: /\.js$|\.ts$|\.tsx$|\.css$|\.html$/,
      minRatio: 1
    })
```

A clue about what's happening ?
Thx a lot

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Respect time of other developers

**Comment by alexander-akait** [comment]
And problem in `extract-css-chunks-webpack-plugin` plugin

**Comment by alexander-akait** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks! Feel free to feedback
