### ISSUE TITLE
Error: No module factory available for dependency type: CssDependency

### ISSUE THREAD

**Issue by DaanDL** [webpack-contrib/mini-css-extract-plugin#739]
- Operating System: Windows 10
- Node Version: v14.16.0
- NPM Version: 7.6.3 [Not of importance here]
- PNPM Version: 6.0.2
- webpack Version: 4.46
- mini-css-extract-plugin Version: 0.9.0
- vue cli Version:  4.5.12

### Expected Behavior

Running pnpm build: which triggers a webpack production build, which uses mini-css-extract-plugin, should build correctly.
**It actually does, when I use Powershell and use `C:/ `instead of `c:/ ` as my starting path.**

### Actual Behavior

I get the following error when my path starts with lowercase `c:/` : 

` ERROR  Error: No module factory available for dependency type: CssDependency
Error: No module factory available for dependency type: CssDependency
    at addDependency (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:800:12)    at iterationOfArrayCallback (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:208:3)
    at addDependenciesBlock (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:816:5)
    at Compilation.processModuleDependencies (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:827:4)
    at afterBuild (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:954:15)
    at C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:998:11
    at callback (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:734:5)
    at C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\Compilation.js:782:12
    at handleParseResult (C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\NormalModule.js:478:12)
    at C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\NormalModule.js:500:6
    at C:\repos\tester2\node_modules\.pnpm\webpack@4.46.0\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\repos\tester2\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\repos\tester2\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\repos\tester2\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:186:6
    at context.callback (C:\repos\tester2\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at c:\repos\tester2\node_modules\.pnpm\mini-css-extract-plugin@0.9.0_webpack@4.46.0\node_modules\mini-css-extract-plugin\dist\loader.js:199:12
 ERROR  Command failed with exit code 1.`

### Code
I already disabled case sensitive plugin in my webpack config like so
```js
module.exports = {
  chainWebpack: config => {
    config.plugins.delete('case-sensitive-paths')
  }
}
```
But that didn't work as well.. 

Installation was done with the shamefully-hoist option active. My .npmrc:
```js
shamefully-hoist=true
```
### How Do We Reproduce?
- vue create testapp
- pnpm build
- remove node_modules and pnpm-lock.yaml, and retry again but this time with your directory path case reversed

**Comment by alexander-akait** [comment]
Update `mini-css-extract-plugin` to the latest stable version, it was fixed for v1, thanks
