### ISSUE TITLE
class CssModule extends webpack.Module

### ISSUE THREAD

**Issue by StasToken** [webpack-contrib/mini-css-extract-plugin#741]
- Operating System: Ubuntu 20.04.1 LTS
- Node Version: v10.19.0
- NPM Version: 6.14.4
- webpack Version: 5.33.2 
- mini-css-extract-plugin Version: ^1.4.1

`npm install --save-dev mini-css-extract-plugin`

_webpack.config.js_

```
var ExtractTextPlugin = require('extract-text-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  entry: './public/js/main.js',
  output: {
    filename: './public/build/bundle.js'
  },
  resolve: {
    modulesDirectories: ['node_modules']
  },
  plugins: [
    new ExtractTextPlugin('./public/build/bundle.css'),
    new MiniCssExtractPlugin(),
  ],
  module: {
    loaders: [
      {
        test: /\.js/,
        loader: 'babel',
        exclude: /(node_modules|bower_components)/
      },
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif|eot|ttf|woff|woff2\?v=4.7.0|woff\?v=4.7.0|eot\?v=4.7.0|ttf\?v=4.7.0|svg\?v=4.7.0|video.play.png)$/,
        type: 'var',
        loader: 'raw-loader',
      },
    ]
  }
};
```

This: [package.json](https://pastebin.com/rneLsUHS)

npm run build

```
> source@1.0.0 build /home/master/project
> webpack

/home/master/project/node_modules/mini-css-extract-plugin/dist/index.js:50
    class CssModule extends webpack.Module {
                                    ^

TypeError: Class extends value undefined is not a constructor or null
    at Function.getCssModule (/home/master/project/node_modules/mini-css-extract-plugin/dist/index.js:50:37)
    at MiniCssExtractPlugin.apply (/home/master/project/node_modules/mini-css-extract-plugin/dist/index.js:358:44)
    at Compiler.apply (/home/master/project/node_modules/tapable/lib/Tapable.js:164:16)
    at WebpackOptionsApply.process (/home/master/project/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/home/master/project/node_modules/webpack/lib/webpack.js:22:48)
    at processOptions (/home/master/project/node_modules/webpack/bin/webpack.js:152:17)
    at Object.<anonymous> (/home/master/project/node_modules/webpack/bin/webpack.js:192:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! source@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the source@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/master/.npm/_logs/2021-04-17T09_33_16_424Z-debug.log
```

WTF? - Explain how to fix it? I was on a bunch of forums and did not find a solution to the problem...

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fix it, respect time of other developers, thanks.

Also, remove this (You don't need this):
```
resolve: {
    modulesDirectories: ['node_modules']
},
```

And remove this (deprecated and should be removed):
```
new ExtractTextPlugin('./public/build/bundle.css'),
```

**Comment by StasToken** [comment]
@alexander-akait - Sorry, I designed my question in accordance with the template, and also provided a repository to quickly reproduce the problem 

- Operating System: Ubuntu 20.04.1 LTS
- Node Version: v10.19.0
- NPM Version: 6.14.4
- webpack Version: 5.33.2
- mini-css-extract-plugin Version: ^1.4.1

### Expected Behavior

Successful project build - Two files should be created
_./public/build/bundle.js
./public/build/bundle.css_

### Actual Behavior
```

> source@1.0.0 build /home/master/project
> webpack

/home/master/project/node_modules/mini-css-extract-plugin/dist/index.js:50
    class CssModule extends webpack.Module {
                                    ^

TypeError: Class extends value undefined is not a constructor or null
    at Function.getCssModule (/home/master/project/node_modules/mini-css-extract-plugin/dist/index.js:50:37)
    at MiniCssExtractPlugin.apply (/home/master/project/node_modules/mini-css-extract-plugin/dist/index.js:358:44)
    at Compiler.apply (/home/master/project/node_modules/tapable/lib/Tapable.js:164:16)
    at WebpackOptionsApply.process (/home/master/project/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/home/master/project/node_modules/webpack/lib/webpack.js:22:48)
    at processOptions (/home/master/project/node_modules/webpack/bin/webpack.js:152:17)
    at Object.<anonymous> (/home/master/project/node_modules/webpack/bin/webpack.js:192:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! source@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the source@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/master/.npm/_logs/2021-04-19T01_50_57_799Z-debug.log
```


### Code

[webpack.config.js](https://gist.github.com/StasToken/ef083478fc5928c0c75b942cf9c5fd01)
[package.json ](https://gist.github.com/StasToken/52a72f23ae364f5e4dbff5838e1be443)

[Repository to quickly reproduce the problem ](https://github.com/StasToken/webpack-error)

**Comment by alexander-akait** [comment]
https://gist.github.com/StasToken/52a72f23ae364f5e4dbff5838e1be443#file-package-json-L15 please use `5` (or `4` version, `1` is not supported)

Configuration for v 5:
```
const MiniCssExtractPlugin  = require('mini-css-extract-plugin');

module.exports = {
  mode: 'development',
  entry: './public/js/main.js',
  output: {
    filename: './public/build/bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.js/,
        loader: 'babel-loader',
        exclude: /(node_modules|bower_components)/
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif|eot|ttf|woff|woff2)$/,
        loader: 'raw-loader',
      },
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // all options are optional
      filename: '[name].css',
      chunkFilename: '[id].css',
      ignoreOrder: false, // Enable to remove warnings about conflicting order
    }),
  ]
};
```

**Comment by StasToken** [comment]
@alexander-akait - Many thanks! - I don’t know how I missed this moment with the version webpack
