### ISSUE TITLE
Module build error when using mini-css-extract-plugin with postcss-loader for .scss file

### ISSUE THREAD

**Issue by chatelp** [webpack-contrib/mini-css-extract-plugin#746]
- Operating System: Homestead v12
- Node Version: 14.16.0
- NPM Version: 6.14.11
- webpack Version: 5
- mini-css-extract-plugin Version: 1.5.0
- postcss-loader Version: 5.2.0

### Actual Behavior

Module build error when using mini-css-extract-plugin with postcss-loader for .scss file. If I remove postcss-loader from the loaders list, then it builds correctly. Problem with mini-css-extract-plugin or postcss-loader ?

### Code

```
ERROR in ./styles/main.scss
Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/postcss-loader/dist/cjs.js):
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss/lib/lazy-result.js:484:33)
    at LazyResult.runAsync (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss/lib/lazy-result.js:372:30)
    at async Object.loader (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss-loader/dist/index.js:87:14)
    at processResult (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/webpack/lib/NormalModule.js:676:19)
    at /home/vagrant/modulor-theme/public/themes/modulor/node_modules/webpack/lib/NormalModule.js:778:5
    at /home/vagrant/modulor-theme/public/themes/modulor/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/vagrant/modulor-theme/public/themes/modulor/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss-loader/dist/index.js:96:7)
```

```js
// extract from webpack.config.js
{
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          { loader: 'css-loader', options: { sourceMap: config.enabled.sourceMaps } },
          {
            loader: 'postcss-loader', options: {
              postcssOptions: {
                config: path.join( __dirname, 'postcss.config.js' ),
                ctx: config,
              },
              sourceMap: config.enabled.sourceMaps,
            },
          },
          { loader: 'resolve-url-loader', options: { sourceMap: config.enabled.sourceMaps } },
          {
            loader: 'sass-loader', options: {
              sassOptions: {
                sourceComments: true,
              },
              sourceMap: true, //config.enabled.sourceMaps, // false causes a resolve issue
            },
          },
        ],
      },
```

```js
// postcss.config.js
/* eslint-disable */

module.exports = (api) => {

  const cssnanoConfig = {
    preset: ['default', { discardComments: { removeAll: true } }]
  };

  return {
    parser: api.options.ctx.enabled.optimize ? 'postcss-safe-parser' : undefined,
    plugins: {
      autoprefixer: true,
      cssnano: api.options.ctx.enabled.optimize ? cssnanoConfig : false,
    },
  };

};
```

**Comment by bodinsamuel** [comment]
Tell me your secret @chatelp 👀
