### ISSUE TITLE
Unable to build with version 2.5.0

### ISSUE THREAD

**Issue by sheshanth** [webpack-contrib/mini-css-extract-plugin#897]
### Actual Behavior
Unable to build with the new miniCssExtractPlugin version `2.5.0`
> error: MiniCssExtractPlugin is not a constructor.
![image](https://user-images.githubusercontent.com/24425933/149621269-5ed32f9a-26bb-4f18-a5ad-ed04c487130b.png)

build is successful while using the previous version `2.4.7`

### Expected Behavior
Expected to build successfully.

### How Do We Reproduce?

repo link: https://github.com/sheshanth/mini-css-plugin.git
1. clone repo using the link above.
2. install dependencies `yarn install` or `npm install`
3. run build `yarn build`or `npm build`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
[webpack-cli] Failed to load 'E:\development\test\webpack.config.js' config
[webpack-cli] TypeError: MiniCssExtractPlugin is not a constructor
    at Object.<anonymous> (E:\development\test\webpack.config.js:18:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at WebpackCLI.tryRequireThenImport (E:\development\test\node_modules\webpack
-cli\lib\webpack-cli.js:244:16)
    at loadConfigByPath (E:\development\test\node_modules\webpack-cli\lib\webpac
k-cli.js:1710:30)
    at WebpackCLI.loadConfig (E:\development\test\node_modules\webpack-cli\lib\w
ebpack-cli.js:1830:36)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by sheshanth** [comment]
duplicate: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896
